name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ./next-startup

            docker compose down
            git restore .
            git pull

            # server            
            echo "NEXT_SERVER_GOOGLE_TOKEN= ${{ secrets.NEXT_SERVER_GOOGLE_TOKEN }}" > .env.local
            echo "NEXT_SERVER_EMAIL_USER= ${{ secrets.NEXT_SERVER_EMAIL_USER }}" >> .env.local
            echo "NEXT_SERVER_EMAIL_PASS= ${{ secrets.NEXT_SERVER_EMAIL_PASS }}" >> .env.local
            echo "NEXT_SERVER_EMAIL_FROM= ${{ secrets.NEXT_SERVER_EMAIL_FROM }}" >> .env.local
            echo "NEXT_SERVER_EMAIL_TO= ${{ secrets.NEXT_SERVER_EMAIL_TO }}" >> .env.local

            docker compose -f docker-compose.prod.yaml build
            docker compose -f docker-compose.prod.yaml up -d